### ISSUE TITLE
投稿の auther とユーザ名の照合処理追加

### ISSUE THREAD

**Issue by technicakidz** [zero-penguin/originalsite_mini#3]
### 概要

投稿者がログインユーザであることを認証させる仕組みを追加/修正する．

**Comment by technicakidz** [comment]
質問メモ
現在，下記などのログインユーザかチェックするための変数定義などをしているが動かない．
https://github.com/zero-penguin/originalsite_mini/blob/939a48e6d28a022ef856073d2626fe9efd979ff5/app.py#L54

https://github.com/zero-penguin/originalsite_mini/blob/939a48e6d28a022ef856073d2626fe9efd979ff5/templates/home.html#L18

A.
ヒントとして `flask-login` ライブラリにあるプロキシ(部品)があることをご紹介しました．
まずはこちらについて使い方含め調べてみてください！

- 公式ドキュメント(英語)
https://flask-login.readthedocs.io/en/latest/#flask_login.current_user

- 実装イメージの参考記事
https://qiita.com/msrks/items/d9c327dd81749ec01d1d#5-%E3%83%AD%E3%82%B0%E3%82%A4%E3%83%B3%E3%83%9A%E3%83%BC%E3%82%B8%E3%81%AEview%E3%82%92%E3%81%A4%E3%81%8F%E3%82%8B

**Comment by zero-penguin** [comment]
改善しました。
かなり以前までは苦戦していましたが、教えてもらった方法でスムーズに行けました。
ありがとうございます。
今後はなるべくすぐに質問した方が良いかもですね
